<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <UsingTask TaskName="Unfucked.BuildInfoGenerator.GenerateBuildInfo" AssemblyFile="$(MSBuildThisFileDirectory)..\tasks\netstandard2.0\Unfucked.BuildInfoGenerator.dll" />
    
    <PropertyGroup>
        <_BuildInfoFilePath>$(IntermediateOutputPath)Unfucked.BuildInfo.g.cs</_BuildInfoFilePath>
    </PropertyGroup>
    
    <Target Name="GenerateBuildInfo" BeforeTargets="BeforeBuild">
        <MakeDir Directories="$(IntermediateOutputPath)" />
        <GenerateBuildInfo ProjectDir="$(MSBuildProjectDirectory)" OutputFile="$(_BuildInfoFilePath)" />
        <!--<Message Text="Wrote build info file $(_BuildInfoFilePath) using DLL" Importance="normal" />-->

        <ItemGroup>
            <Compile Include="$(_BuildInfoFilePath)" />
        </ItemGroup>
    </Target>

    <Target Name="CleanBuildInfo" AfterTargets="AfterClean">
        <Delete Files="$(_BuildInfoFilePath)" />
    </Target>

</Project>