<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net47;net6.0;net8.0;net9.0</TargetFrameworks>
        <Version>$(UnfuckedVersion)</Version> <!-- Defined in ..\Directory.Build.props -->
        <AssemblyName>$(MSBuildProjectName)</AssemblyName>
        <RootNamespace>$(MSBuildProjectName)</RootNamespace>
        <Description>Fix egregiously broken or missing functionality in .NET libraries. Provide useful boilerplate, façades, and polyfills.</Description>
        <NoWarn>$(NoWarn);SYSLIB1054;NU5100</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="..\Unfucked\icon.png" />
        <None Include="..\Unfucked\icon.png" Pack="true" PackagePath="\" Visible="true" />
        <None Include="..\*.props;..\*.ps1;..\.github*\**" />
        <AdditionalFiles Include="..\ExceptionAdjustments.txt" Visible="true" />
        <None Include="GenerateBuildInfo.targets" Pack="true" PackagePath="buildTransitive\$(PackageId).targets" />
    </ItemGroup>

    <ItemGroup Condition="$([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')) == '.NETStandard' or $([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')) == '.NETFramework'">
        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
        <PackageReference Include="System.Collections.Immutable" />
        <PackageReference Include="System.Threading.Tasks.Dataflow" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup Condition="$([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')) == '.NETFramework'">
        <Reference Include="System.Net.Http" />
        <Reference Include="System.Web" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" IncludeAssets="compile" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BuildInfoGenerator\BuildInfoGenerator.csproj" PrivateAssets="all" ExcludeAssets="all" />
        <None Include="$(OutputPath)\netstandard2.0\Unfucked.BuildInfoGenerator.dll" Pack="true" PackagePath="tasks\netstandard2.0" Visible="false" />
    </ItemGroup>

</Project>